language: bash

os:
  - linux

install:
  - sudo apt install shellcheck;
 
script:
  - bash ./tests/test_shell_linting.sh

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
